apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: httpd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-pod
  template:
    metadata:
      labels:
        app: httpd-pod
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80
